# Generated by Django 3.1 on 2020-08-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20200819_1711'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='Followers',
        ),
    ]
