# Generated by Django 3.1 on 2020-08-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20200819_1712'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='followers',
            constraint=models.UniqueConstraint(fields=('user', 'followed'), name='unq_user_followed'),
        ),
    ]
