# Generated by Django 3.1 on 2020-08-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20200824_0532'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followers',
            new_name='Follower',
        ),
        migrations.RenameModel(
            old_name='Reactions',
            new_name='Like',
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
        migrations.RemoveConstraint(
            model_name='follower',
            name='unq_user_followed',
        ),
        migrations.RemoveConstraint(
            model_name='like',
            name='unq_user_liked',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='liked',
            new_name='post',
        ),
        migrations.AddConstraint(
            model_name='follower',
            constraint=models.UniqueConstraint(
                fields=('user', 'followed'), name='unq_user_follower'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(
                fields=('user', 'post'), name='unq_user_likes'),
        ),
    ]
