# Generated by Django 3.1 on 2020-08-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20200824_0557'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='unq_user_likes',
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unq_user_likes'),
        ),
    ]
