name: Unit test for social network
on: push
  brances:
    - '*'
    - '!deploy'
jobs:
  test_network:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Unit Tests for Network
        run: |
          pip3 install -r requirements.txt
          python3 manage.py test
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
